services:
  postgres:
    image: postgres
    container_name: todo-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=satheesan
      - POSTGRES_USER=postgres
    networks:
      - todo_network
    volumes:
      - todo_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  todo-api-gateway:
    image: akhi9550/todo-api
    restart: always
    container_name: todo-api
    networks:
      - todo_network
    ports:
      - "5000:5000"

  todo-services:
    image: akhi9550/todo-service
    restart: always
    depends_on:
      - postgres
    container_name: todo-service
    networks:
      - todo_network
    hostname: todo-service

networks:
  todo_network:
    driver: bridge

volumes:
  todo_volume:
